// <auto-generated />
using System;
using MetrcDatabaseWriter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetrcDatabaseWriter.Migrations
{
    [DbContext(typeof(MetrcSQLContext))]
    [Migration("20250107223226_AddNullable_LabTestResult_CompoundName-CompoundType")]
    partial class AddNullable_LabTestResult_CompoundNameCompoundType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetrcDatabaseWriter.Facility", b =>
                {
                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AdvancedSales")
                        .HasColumnType("bit");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanAdjustSourcePackagesWithPartials")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAssignLocationsToPackages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAssignLocationsToPlantBatches")
                        .HasColumnType("bit");

                    b.Property<bool>("CanClonePlantBatches")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateDerivedPackages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateImmaturePlantPackagesFromPlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateOpeningBalancePackages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateOpeningBalancePlantBatches")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreatePartialPackages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateProcessValidationPackages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateTradeSamplePackages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeliverSalesToConsumers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeliverSalesToPatients")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDestroyProduct")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDonatePackages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanGenerateProductLabel")
                        .HasColumnType("bit");

                    b.Property<bool>("CanGrowPlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanHaveMemberPatients")
                        .HasColumnType("bit");

                    b.Property<bool>("CanInfuseProducts")
                        .HasColumnType("bit");

                    b.Property<bool>("CanPackageVegetativePlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanPackageWaste")
                        .HasColumnType("bit");

                    b.Property<bool>("CanPrintProductLabel")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReceiveAssociateProductLabel")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRecordProcessingJobs")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRecordProductForDestruction")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRemediatePackagesWithFailedLabResults")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReportAdulteration")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReportHarvestSchedules")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReportOperationalExceptions")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReportPatientCheckIns")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReportPatientsAdverseResponses")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReportStrainProperties")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRequestProductRemediation")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRequireHarvestSampleLabTestBatches")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRequirePackageSampleLabTestBatches")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSellFromPackagesOnTrip")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSellToCaregivers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSellToConsumers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSellToExternalPatients")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSellToPatients")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSpecifyPatientSalesLimitExemption")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSubmitHarvestsForTesting")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSubmitPackagesForTesting")
                        .HasColumnType("bit");

                    b.Property<bool>("CanTagPlantBatches")
                        .HasColumnType("bit");

                    b.Property<bool>("CanTakeHarvestsOnTrip")
                        .HasColumnType("bit");

                    b.Property<bool>("CanTakePackagesOnTrip")
                        .HasColumnType("bit");

                    b.Property<bool>("CanTakePlantBatchesOnTrip")
                        .HasColumnType("bit");

                    b.Property<bool>("CanTakePlantsOnTrip")
                        .HasColumnType("bit");

                    b.Property<bool>("CanTestPackages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanTrackVegetativePlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanTransferFromExternalFacilities")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdateLocationsOnPackages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdatePlantStrains")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CredentialedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HireDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHemp")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMedical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRetail")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSalesDeliveryHub")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PackagesRequirePatientAffiliation")
                        .HasColumnType("bit");

                    b.Property<bool>("PlantBatchesCanContainMotherPlants")
                        .HasColumnType("bit");

                    b.Property<bool>("PlantsRequirePatientAffiliation")
                        .HasColumnType("bit");

                    b.Property<int?>("RestrictHarvestPlantRestoreTimeHours")
                        .HasColumnType("int");

                    b.Property<int?>("RestrictPlantBatchAdjustmentTimeHours")
                        .HasColumnType("int");

                    b.Property<int?>("RestrictWholesalePriceEditDays")
                        .HasColumnType("int");

                    b.Property<bool>("RetailerDelivery")
                        .HasColumnType("bit");

                    b.Property<bool>("RetailerDeliveryAllowDonations")
                        .HasColumnType("bit");

                    b.Property<bool>("RetailerDeliveryAllowPartialPackages")
                        .HasColumnType("bit");

                    b.Property<bool>("RetailerDeliveryAllowTradeSamples")
                        .HasColumnType("bit");

                    b.Property<bool>("RetailerDeliveryRequirePrice")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesDeliveryAllowAddress")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesDeliveryAllowCity")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesDeliveryAllowCounty")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesDeliveryAllowPlannedRoute")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesDeliveryAllowState")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesDeliveryAllowZip")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesDeliveryRequireConsumerId")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesDeliveryRequirePatientNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesDeliveryRequireRecipientName")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesRequireCaregiverNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesRequireCaregiverPatientNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesRequireExternalPatientIdentificationMethod")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesRequireExternalPatientNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesRequirePatientNumber")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SupportActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SupportExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SupportLastPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TestsRequireLabSample")
                        .HasColumnType("bit");

                    b.Property<int?>("TotalMemberPatientsAllowed")
                        .HasColumnType("int");

                    b.HasKey("LicenseNumber");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("MetrcDatabaseWriter.Harvest", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FacilityLicense")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ArchivedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentWeight")
                        .HasColumnType("float");

                    b.Property<int>("DryingLocationId")
                        .HasColumnType("int");

                    b.Property<string>("DryingLocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DryingLocationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HarvestStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HarvestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnHold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnTrip")
                        .HasColumnType("bit");

                    b.Property<string>("LabTestingState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LabTestingStateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageCount")
                        .HasColumnType("int");

                    b.Property<string>("PatientLicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantCount")
                        .HasColumnType("int");

                    b.Property<int>("SourceStrainCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceStrainNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPackagedWeight")
                        .HasColumnType("float");

                    b.Property<double>("TotalRestoredWeight")
                        .HasColumnType("float");

                    b.Property<double>("TotalWasteWeight")
                        .HasColumnType("float");

                    b.Property<double>("TotalWetWeight")
                        .HasColumnType("float");

                    b.Property<string>("UnitOfWeightName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "FacilityLicense");

                    b.HasIndex("FacilityLicense");

                    b.ToTable("Harvest");
                });

            modelBuilder.Entity("MetrcDatabaseWriter.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FacilityLicense")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdministrationMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApprovalStatusDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultLabTestingState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasExpirationDate")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSellByDate")
                        .HasColumnType("bit");

                    b.Property<bool>("HasUseByDate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpirationDateRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSellByDateRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUseByDateRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemBrandId")
                        .HasColumnType("int");

                    b.Property<string>("ItemBrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelPhotoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfDoses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackagingImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackagingPhotoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCategoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductPDFDocuments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductPhotoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicIngredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuantityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServingSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StrainId")
                        .HasColumnType("int");

                    b.Property<string>("StrainName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplyDurationDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitCbdContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitCbdContentDose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitCbdContentDoseUnitOfMeasureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitCbdContentUnitOfMeasureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitCbdPercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitQuantityUnitOfMeasureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitThcContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitThcContentDose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitThcContentDoseUnitOfMeasureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitThcContentUnitOfMeasureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitThcPercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitVolume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitVolumeUnitOfMeasureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitWeightUnitOfMeasureName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "FacilityLicense");

                    b.HasIndex("FacilityLicense");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("MetrcDatabaseWriter.LabTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompoundName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LabFacilityLicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabFacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LabTestDetailRevokedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LabTestResultId")
                        .HasColumnType("int");

                    b.Property<int>("LabTestTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("OverallPassed")
                        .HasColumnType("bit");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResultReleaseDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ResultReleased")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourcePackageLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestBatchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TestInformationalOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("TestPassed")
                        .HasColumnType("bit");

                    b.Property<string>("TestPerformedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TestResultLevel")
                        .HasColumnType("float");

                    b.Property<string>("TestTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LabTestResultId");

                    b.HasIndex("PackageId");

                    b.ToTable("LabTestResult");
                });

            modelBuilder.Entity("MetrcDatabaseWriter.LabTestType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FacilityLicense")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AlwaysPasses")
                        .HasColumnType("bit");

                    b.Property<string>("DependencyMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InformationalOnly")
                        .HasColumnType("bit");

                    b.Property<int?>("LabTestResultExpirationDays")
                        .HasColumnType("int");

                    b.Property<double>("LabTestResultMaximum")
                        .HasColumnType("float");

                    b.Property<double>("LabTestResultMinimum")
                        .HasColumnType("float");

                    b.Property<string>("LabTestResultMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAllowedFailureCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresTestResult")
                        .HasColumnType("bit");

                    b.HasKey("Id", "FacilityLicense");

                    b.HasIndex("FacilityLicense");

                    b.ToTable("LabTestType");
                });

            modelBuilder.Entity("MetrcDatabaseWriter.Package", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FacilityLicense")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ArchivedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ContainsRemediatedProduct")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitialLabTestingState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDonation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDonationPersistent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnHold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnRetailerDelivery")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnTrip")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcessValidationTestingSample")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProductionBatch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTestingSample")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTradeSample")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTradeSamplePersistent")
                        .HasColumnType("bit");

                    b.Property<string>("ItemFromFacilityLicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemFromFacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LabTestResultExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LabTestingRecordedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LabTestingState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabTestingStateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageForProductDestruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackagedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientLicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProductRequiresRemediation")
                        .HasColumnType("bit");

                    b.Property<string>("ProductionBatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ReceivedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceivedFromFacilityLicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedFromFacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedFromManifestNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemediationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SellByDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SourceHarvestCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceHarvestNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourcePackageCount")
                        .HasColumnType("int");

                    b.Property<bool>("SourcePackageIsDonation")
                        .HasColumnType("bit");

                    b.Property<bool>("SourcePackageIsTradeSample")
                        .HasColumnType("bit");

                    b.Property<string>("SourcePackageLabels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceProcessingJobCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceProductionBatchNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasureAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UseByDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id", "FacilityLicense");

                    b.HasIndex("FacilityLicense");

                    b.HasIndex("ItemId");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("MetrcDatabaseWriter.Strain", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FacilityLicense")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("CbdLevel")
                        .HasColumnType("float");

                    b.Property<string>("Genetics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IndicaPercentage")
                        .HasColumnType("float");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SativaPercentage")
                        .HasColumnType("float");

                    b.Property<string>("TestingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ThcLevel")
                        .HasColumnType("float");

                    b.HasKey("Id", "FacilityLicense");

                    b.HasIndex("FacilityLicense");

                    b.ToTable("Strain");
                });

            modelBuilder.Entity("MetrcDatabaseWriter.Harvest", b =>
                {
                    b.HasOne("MetrcDatabaseWriter.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityLicense")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MetrcDatabaseWriter.Item", b =>
                {
                    b.HasOne("MetrcDatabaseWriter.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityLicense")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MetrcDatabaseWriter.LabTestResult", b =>
                {
                    b.HasOne("MetrcDatabaseWriter.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MetrcDatabaseWriter.LabTestType", b =>
                {
                    b.HasOne("MetrcDatabaseWriter.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityLicense")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MetrcDatabaseWriter.Package", b =>
                {
                    b.HasOne("MetrcDatabaseWriter.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityLicense")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetrcDatabaseWriter.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .HasPrincipalKey("Id");
                });

            modelBuilder.Entity("MetrcDatabaseWriter.Strain", b =>
                {
                    b.HasOne("MetrcDatabaseWriter.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityLicense")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
